---
name: Agile
full_name: Agile Guild
mission: To improve the quality and speed of service delivery through process
  improvement by encouraging the use of iterative methods in the research,
  planning, design and development of solutions we implement.
status: active
private:
  slack: g-agile
  drive: https://drive.google.com/drive/folders/0B_n2YScccqDXfjRNN0JXdFNYYzhqLWJJN0JCRW12SGQ3emkzc1BqMmZYRi1ZTjdRY2xwclU
  charter: https://docs.google.com/document/d/1NJYy34sOc1NdcQ9f1NZJZg-RGgu5ey0UQ1SugwE9Vlo/edit
leads:
- sarah
members:
- sarah
- bret
- jessie
- david
owner_type: guild
